### ISSUE TITLE
Project died

### ISSUE THREAD

**Issue by stephanielha** [chjno/MEDP349-Fall17#14]
I'm not even sure how to describe what happened. It was working and now it isn't, the sketch turns white. The values are printing in the serial monitor but the p5.js sketch isn't changing. I'm not even sure if it's a glitch or typo. I keep trying to restart the arduino or sending the code again, nothing works. 

var portName = 'COM4';
var serial;

var ry;
var ysen;
var rx = 300;
var rxy = -300;

function setup() { 
  createCanvas(400, 400);
  
  serial = new p5.SerialPort();
  serial.open(portName);
  serial.on('data', parseData);
  
  ysen = 300;
  ry = height;

} 

function draw() { 
  background(255);
  
  noStroke();
  fill('black');
  rect(0, ysen, width, height);
  
  noStroke();
  fill('yellow');
  rect(0, ry, width, height);
  
  fill('blue');
  rect(rx, 0, width, height);
  
  fill('red');
  rect(rxy, 0, width, height);
}

function parseData(){
  var data = serial.readLine();
  if (data.length > 0){
    print(data);
    
    var values = data.split(',');
    
    var offset = map(int(values[0]), 0, 1023, 0, 200);
    rx = offset - 300;

    
    var offset = map(int(values[1]), 0, 1023, 0, height);
    ry = height - offset;
    
    var offset = map(int(values[0]), 0, 1023, 0, height);
    ysen = 0 - offset;
    
    var offset = map(int(values[1]), 0, 1023, 0, 200);
    rxy = offset + 300;
    
    
  }
}

**Comment by chjno** [comment]
I'm guessing you figured it out since you closed the issue? LMK if you still need help with this.
