### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by emilyjacob96** [chjno/MEDP349-Fall17#8]
It was very hard initially, but I simply wanted to make the button work and eventually I tried to advance in having the LED light blink on its own without the button pressed. But I was unsuccessful, yet I took whatever example I could take from class and incorporated into this assignment. 

https://vimeo.com/237691445 

![button1](https://user-images.githubusercontent.com/31677718/31424222-145df796-ae27-11e7-841e-45e5e6ff88c6.JPG)
![button2](https://user-images.githubusercontent.com/31677718/31424225-161f95ee-ae27-11e7-82d2-d81c6cbf1773.JPG)
![button3](https://user-images.githubusercontent.com/31677718/31424227-17460336-ae27-11e7-80b4-4c47683288e4.JPG)

**Comment by chjno** [comment]
hey emily, can you please move this to the wiki? please see instructions on previous assignments on creating homework posts.
